### ISSUE TITLE
[0.3.4A2] [Techniclauncher] Registering textures crash

### ISSUE THREAD

**Issue by foreverAGnome** [erogenousbeef/BigReactors#392]
I am using BigReactors with 11 other mods in a stripped-down version of Attack of the B-Team (the full pack lags too much and I don't really use all of the mods) and when I try to launch the pack, it crashes and gives the following crash report:

---- Minecraft Crash Report ----
// Don't do that.

Time: 11/29/14 10:38 AM
Description: Registering texture

java.lang.ArrayIndexOutOfBoundsException: 2
    at erogenousbeef.bigreactors.common.multiblock.block.BlockMultiblockGlass.func_71858_a(BlockMultiblockGlass.java:109)
    at codechicken.microblock.BlockMicroMaterial$$anonfun$loadIcons$2.apply$mcVI$sp(BlockMicroMaterial.scala:43)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
    at codechicken.microblock.BlockMicroMaterial.loadIcons(BlockMicroMaterial.scala:42)
    at codechicken.microblock.handler.MicroblockEventHandler$$anonfun$postTextureStitch$1.apply(MicroblockEventHandler.scala:31)
    at codechicken.microblock.handler.MicroblockEventHandler$$anonfun$postTextureStitch$1.apply(MicroblockEventHandler.scala:31)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
    at codechicken.microblock.handler.MicroblockEventHandler$.postTextureStitch(MicroblockEventHandler.scala:31)
    at net.minecraftforge.event.ASMEventHandler_57_MicroblockEventHandler$_postTextureStitch_Post.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
    at net.minecraftforge.event.EventBus.post(EventBus.java:108)
    at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPost(ForgeHooksClient.java:252)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:149)
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:57)
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:69)
    at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:133)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SourceFile:99)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SourceFile:87)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:543)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:265)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:509)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at erogenousbeef.bigreactors.common.multiblock.block.BlockMultiblockGlass.func_71858_a(BlockMultiblockGlass.java:109)
    at codechicken.microblock.BlockMicroMaterial$$anonfun$loadIcons$2.apply$mcVI$sp(BlockMicroMaterial.scala:43)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
    at codechicken.microblock.BlockMicroMaterial.loadIcons(BlockMicroMaterial.scala:42)
    at codechicken.microblock.handler.MicroblockEventHandler$$anonfun$postTextureStitch$1.apply(MicroblockEventHandler.scala:31)
    at codechicken.microblock.handler.MicroblockEventHandler$$anonfun$postTextureStitch$1.apply(MicroblockEventHandler.scala:31)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
    at codechicken.microblock.handler.MicroblockEventHandler$.postTextureStitch(MicroblockEventHandler.scala:31)
    at net.minecraftforge.event.ASMEventHandler_57_MicroblockEventHandler$_postTextureStitch_Post.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
    at net.minecraftforge.event.EventBus.post(EventBus.java:108)
    at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPost(ForgeHooksClient.java:252)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:149)
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:57)

-- Resource location being registered --
Details:
    Resource location: minecraft:textures/atlas/blocks.png
    Texture object class: net.minecraft.client.renderer.texture.TextureMap
Stacktrace:
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:69)
    at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:133)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SourceFile:99)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SourceFile:87)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:543)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:265)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:509)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Mac OS X (x86_64) version 10.8.5
    Java Version: 1.7.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 221162032 bytes (210 MB) / 570425344 bytes (544 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -Xmx1024m -XX:MaxPermSize=128m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 41 mods loaded, 41 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{6.4.49.965} [Forge Mod Loader](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{9.11.1.965} [Minecraft Forge](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore{0.9.0.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AppliedEnergistics-Core{rv14.finale3} [AppliedEnergistics Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems{1.6.1.9} [Not Enough Items](notenoughitems 1.6.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct-Preloader{0.0.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AppliedEnergistics{rv14.finale3} [Applied Energistics](appeng-rv14-finale3-mc16x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiblioCraft{1.5.5} [BiblioCraft](bibliocraft[v1.5.5].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHCore{2.0.0.5} [CoFH Core](cofhcore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMultipart{1.0.1.268} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Core{4.2.2} [BuildCraft](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThermalExpansion{3.0.0.7} [Thermal Expansion](thermalexpansion-3.0.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BigReactors{0.3.4A2} [Big Reactors](BigReactors-0.3.4A2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Builders{4.2.2} [BC Builders](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Energy{4.2.2} [BC Energy](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Factory{4.2.2} [BC Factory](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Transport{4.2.2} [BC Transport](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Silicon{4.2.2} [BC Silicon](buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CarpentersBlocks{2.1.0} [Carpenter's Blocks](carpentersblocks v2.1.0 - MC 1.6+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHLoot{2.0.0.5} [CoFH Loot](cofhcore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHMasquerade{2.0.0.5} [CoFH Masquerade](cofhcore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHSocial{2.0.0.5} [CoFH Social](cofhcore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHWorld{2.0.0.5} [CoFH World](cofhcore-2.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NEIPlugins{1.1.0.6} [NEI Plugins](neiplugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughCodecs{0.1} [NotEnoughCodecs](notenoughcodecs-0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    notenoughkeys{0.0.4} [Not Enough Keys](notenoughkeys-1.6.4-0.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Core{4.3.7.32} [ProjectRed](projectredbase-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Transmission{4.3.7.32} [ProjectRed-Transmission](projectredintegration-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Transportation{4.3.7.32} [ProjectRed-Transportation](projectredmechanical-BETA-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Exploration{4.3.7.32} [ProjectRed-Exploration](projectredworld-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Waila{1.5.2a} [Waila](waila_1.5.2a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct{1.6.X_1.5.5.7} [Tinkers' Construct](tconstruct_mc1.6.4_1.5.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Compatibility{4.3.7.32} [ProjectRed-Compatibility](projectredcompat-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Integration{4.3.7.32} [ProjectRed-Integration](projectredintegration-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Illumination{4.3.7.32} [ProjectRed-Illumination](projectredlighting-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ProjRed|Expansion{4.3.7.32} [ProjectRed-Expansion](projectredmechanical-BETA-1.6.4-4.3.7.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    simplyjetpacks{0.3.1.1} [Simply Jetpacks](SimplyJetpacks-0.3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    witchery{0.19.2} [Witchery](witchery-1.6.4-0.19.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    McMultipart{1.0.1.268} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForgeMicroblock{1.0.1.268} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct Environment: Environment seems clean, however you are using a modpack; please report it to the pack author, not us!
    Launched Version: 1.6.4-Forge9.11.1.965
    LWJGL: 2.9.0
    OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-8.16.80, Intel Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
##     Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

I checked the source code (I know a medium amount of Java, but I'm no expert) and the problem seems to be that codechicken is trying to get to an array entry that isn't there. I'm using Codechicken 9.0.9 and BigReactors 0.3.4A2 with minecraft 1.6.4. I hope that I didn't bother you with a personal problem and I think that it may be an issue with BigReactors and other mods (Witchery has been picky with me in the past) not playing nice, but I hope you'll take the time to help me if it is just a personal problem. Thanks in advance!

**Comment by cyanidearsenic** [comment]
I'm having the same error as the user above but I can't find anything in the config file called multiblock glass. In fact, I can't find any item IDs for Big Reactors. Is there a separate config file that covers that and isn't found inside the Big Reactors folder in the config folder.

**Comment by cyanidearsenic** [comment]
.?

**Comment by Frontrider** [comment]
If you use 1.7, then there is no id config to worry about.
If not use 1.7 to prevent this issue.

**Comment by cyanidearsenic** [comment]
Okay, thank you.
