### ISSUE TITLE
Thermal Dynamics compatability

### ISSUE THREAD

**Issue by jetravis** [erogenousbeef/BigReactors#454]
I get the following error in the crash report when trying to use a big reactor with one of the new flux-plated fluiducts

java.lang.ClassCastException: erogenousbeef.bigreactors.common.multiblock.tileentity.TileEntityReactorPowerTap cannot be cast to cofh.api.energy.IEnergyReceiver
	at cofh.thermaldynamics.ducts.fluid.TileFluidDuctFlux.cacheStructural(TileFluidDuctFlux.java:162)
	at cofh.thermaldynamics.block.TileMultiBlock.handleSideUpdate(TileMultiBlock.java:394)
	at cofh.thermaldynamics.block.TileMultiBlock.onNeighborTileChange(TileMultiBlock.java:470)
	at cofh.thermaldynamics.ducts.fluid.TileFluidDuctFlux.onNeighborTileChange(TileFluidDuctFlux.java:57)
	at cofh.core.block.BlockCoFHBase.onNeighborChange(BlockCoFHBase.java:189)
	at net.minecraft.world.World.func_147453_f(World.java:3875)
	at erogenousbeef.core.multiblock.MultiblockTileEntityBase.notifyNeighborsOfTileChange(MultiblockTileEntityBase.java:338)
	at erogenousbeef.bigreactors.common.multiblock.tileentity.TileEntityReactorPowerTap.onMachineAssembled(TileEntityReactorPowerTap.java:51)
	at erogenousbeef.core.multiblock.MultiblockControllerBase.assembleMachine(MultiblockControllerBase.java:336)
	at erogenousbeef.core.multiblock.MultiblockControllerBase.checkIfMachineIsWhole(MultiblockControllerBase.java:320)
	at erogenousbeef.core.multiblock.MultiblockWorldRegistry.tickEnd(MultiblockWorldRegistry.java:222)
	at erogenousbeef.core.multiblock.MultiblockRegistry.tickEnd(MultiblockRegistry.java:36)
	at erogenousbeef.core.multiblock.MultiblockServerTickHandler.onWorldTick(MultiblockServerTickHandler.java:22)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_589_MultiblockServerTickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Frontrider** [comment]
Must be latest cohf core, latest big reactors?

**Comment by jetravis** [comment]
It's FTB Infinity 1.2.0.

Bigreactors 0.4.1A2
Thermal Dynamics 1.0.0RC1-69
COFH Core 3.0.0RC1-181

Also reproduced with version 0.4.2A2 with no other changes. It seems to only be the flux-plated fluiducts and not any other version of the ducts.

**Comment by Frontrider** [comment]
sent it to the other side as well? Its might be a bug in thermal dynamics.

**Comment by erogenousbeef** [comment]
There's most likely been an API change in the new versions of the CoFH Energy interfaces. I expect I need to update BR's Energy interfaces to work with the RC1 versions of the CoFH mods.

**Comment by erogenousbeef** [comment]
Going to do the best I can do get something out for this, but this is a _really_ busy week.

**Comment by KingLemming** [comment]
The API change has been in for months. This isn't anything new.

**Comment by erogenousbeef** [comment]
@KingLemming has fixed this in Thermal Dynamics, please upgrade to Thermal Dynamics 3.0.0 RC5 (or newer).
