### ISSUE TITLE
possible sideness fail

### ISSUE THREAD

**Issue by goreacraft** [erogenousbeef/BigReactors#460]
Forge Mod Loader version 7.10.85.1286 for Minecraft 1.7.10 loading
Java is OpenJDK 64-Bit Server VM, version 1.7.0_75, running on Linux:amd64:3.10.23-xxxx-std-ipv6-64, installed at /usr/lib/jvm/java-7-openjdk-amd64/jre
Modpack FTB Infinity 1.2.1 -> BigReactors-0.4.1A2

---------------------------------------------------------------------------------------------------------------------------
[12:12:54] [Server thread/ERROR]: Unable to add included methods from class class erogenousbeef.bigreactors.common.tileentity.base.TileEntityBeefBase (possible sideness fail)
java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.7.0_75]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2615) ~[?:1.7.0_75]
	at java.lang.Class.privateGetPublicMethods(Class.java:2733) ~[?:1.7.0_75]
	at java.lang.Class.privateGetPublicMethods(Class.java:2743) ~[?:1.7.0_75]
	at java.lang.Class.getMethods(Class.java:1472) ~[?:1.7.0_75]
	at openperipheral.adapter.peripheral.PeripheralAdapterWrapper.buildMethodList(PeripheralAdapterWrapper.java:91) [PeripheralAdapterWrapper.class:?]
	at openperipheral.adapter.peripheral.PeripheralInlineAdapterWrapper.buildMethodList(PeripheralInlineAdapterWrapper.java:99) [PeripheralInlineAdapterWrapper.class:?]
	at openperipheral.adapter.AdapterWrapper.<init>(AdapterWrapper.java:32) [AdapterWrapper.class:?]
	at openperipheral.adapter.peripheral.PeripheralAdapterWrapper.<init>(PeripheralAdapterWrapper.java:27) [PeripheralAdapterWrapper.class:?]
	at openperipheral.adapter.peripheral.PeripheralInlineAdapterWrapper.<init>(PeripheralInlineAdapterWrapper.java:38) [PeripheralInlineAdapterWrapper.class:?]
	at openperipheral.adapter.peripheral.PeripheralInlineAdapterWrapper.<init>(PeripheralInlineAdapterWrapper.java:34) [PeripheralInlineAdapterWrapper.class:?]
	at openperipheral.adapter.AdapterManager$4.wrapInlineAdapter(AdapterManager.java:80) [AdapterManager$4.class:?]
	at openperipheral.adapter.AdapterManager.getInlineAdapter(AdapterManager.java:167) [AdapterManager.class:?]
	at openperipheral.adapter.composed.ClassMethodsListBuilder.addInlineAdapter(ClassMethodsListBuilder.java:49) [ClassMethodsListBuilder.class:?]
	at openperipheral.adapter.composed.ClassMethodsComposer.createMethodsList(ClassMethodsComposer.java:29) [ClassMethodsComposer.class:?]
	at openperipheral.adapter.AdapterManager$4.collectMethods(AdapterManager.java:68) [AdapterManager$4.class:?]
	at openperipheral.adapter.AdapterManager.getAdaptedClass(AdapterManager.java:148) [AdapterManager.class:?]
	at openperipheral.adapter.PeripheralHandlers.createAdaptedPeripheral(PeripheralHandlers.java:120) [PeripheralHandlers.class:?]
	at openperipheral.adapter.PeripheralHandlers$3.createPeripheral(PeripheralHandlers.java:47) [PeripheralHandlers$3.class:?]
	at openperipheral.adapter.SafePeripheralFactory.getPeripheral(SafePeripheralFactory.java:69) [SafePeripheralFactory.class:?]
	at openperipheral.adapter.CachingPeripheralFactory.getPeripheral(CachingPeripheralFactory.java:19) [CachingPeripheralFactory.class:?]
	at openperipheral.adapter.CachingPeripheralFactory.getPeripheral(CachingPeripheralFactory.java:9) [CachingPeripheralFactory.class:?]
	at openperipheral.adapter.PeripheralHandlers.getPeripheral(PeripheralHandlers.java:149) [PeripheralHandlers.class:?]
	at dan200.computercraft.ComputerCraft.getPeripheralAt(ComputerCraft.java:394) [ComputerCraft.class:?]
	at dan200.computercraft.shared.util.PeripheralUtil.getPeripheral(PeripheralUtil.java:13) [PeripheralUtil.class:?]
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateInput(TileComputerBase.java:317) [TileComputerBase.class:?]
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.createServerComputer(TileComputerBase.java:420) [TileComputerBase.class:?]
	at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_145845_h(TileComputerBase.java:187) [TileComputerBase.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2491) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
	... 35 more
Caused by: java.lang.RuntimeException: Attempted to load class bdw for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:51) ~[cauldron-1.7.10-1.1286.06.216-server.jar:git-Cauldron-MCPC-Plus-1.7.10-1.1286.06.216]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
	... 35 more

**Comment by erogenousbeef** [comment]
This looks like an OpenPeripheral problem; I don't think they're respecting Forge's `SideOnly` attribute.
