### ISSUE TITLE
Crash while using turbine

### ISSUE THREAD

**Issue by ColdPhoenix** [erogenousbeef/BigReactors#510]
Crash report:
---- Minecraft Crash Report ----
// Why did you do that?

Time: 24.06.15 21:01
Description: Unexpected error

java.lang.IllegalStateException: Already tesselating!
    at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
    at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
    at net.minecraft.client.particle.EffectRenderer.func_78874_a(EffectRenderer.java:147)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1617)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1305)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
    at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
    at net.minecraft.client.particle.EffectRenderer.func_78874_a(EffectRenderer.java:147)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1617)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [GCEntityClientPlayerMP['ColdPhoenix'/14, l='MpServer', x=1755,79, y=63,89, z=453,71]]
    Chunk stats: MultiplayerChunkCache: 289, 298
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (1739,4,463), Chunk: (at 11,0,15 in 108,28; contains blocks 1728,0,448 to 1743,255,463), Region: (3,0; contains chunks 96,0 to 127,31, blocks 1536,0,0 to 2047,255,511)
    Level time: 17924 game time, 17924 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 37 total; [EntityCreeper['Creeper'/6976, l='MpServer', x=1719,50, y=56,00, z=528,50], EntityZombie['Zombie'/6788, l='MpServer', x=1680,50, y=56,00, z=468,50], EntitySpider['Spider'/6214, l='MpServer', x=1814,66, y=56,00, z=453,00], EntitySkeleton['Skeleton'/6790, l='MpServer', x=1760,50, y=56,00, z=411,50], EntitySkeleton['Skeleton'/6791, l='MpServer', x=1676,50, y=56,00, z=472,50], EntityCreeper['Creeper'/4680, l='MpServer', x=1733,53, y=56,00, z=456,78], EntitySkeleton['Skeleton'/6792, l='MpServer', x=1675,50, y=56,00, z=474,50], EntityZombie['Zombie'/6537, l='MpServer', x=1766,75, y=56,00, z=465,78], EntitySpider['Spider'/6221, l='MpServer', x=1832,50, y=56,00, z=397,50], GCEntityClientPlayerMP['ColdPhoenix'/14, l='MpServer', x=1755,79, y=63,89, z=453,71], EntitySpider['Spider'/6742, l='MpServer', x=1705,50, y=56,00, z=513,81], EntitySpider['Spider'/6743, l='MpServer', x=1682,91, y=56,00, z=416,56], EntitySpider['Spider'/6744, l='MpServer', x=1756,50, y=56,00, z=408,50], EntitySkeleton['Skeleton'/6632, l='MpServer', x=1780,50, y=56,00, z=391,50], EntitySpider['Spider'/6122, l='MpServer', x=1811,75, y=56,00, z=447,25], EntitySpider['Spider'/6570, l='MpServer', x=1833,50, y=56,00, z=387,50], EntitySpider['Spider'/6635, l='MpServer', x=1764,13, y=56,00, z=397,22], EntityItem['item.item.dyePowder.black'/4014, l='MpServer', x=1787,41, y=54,13, z=449,72], EntityCreeper['Creeper'/6574, l='MpServer', x=1764,03, y=56,00, z=402,50], EntitySpider['Spider'/6575, l='MpServer', x=1722,06, y=56,00, z=486,03], EntitySpider['Spider'/6576, l='MpServer', x=1728,50, y=56,00, z=490,56], EntitySpider['Spider'/6640, l='MpServer', x=1766,44, y=56,00, z=401,19], EntitySpider['Spider'/6577, l='MpServer', x=1738,59, y=56,00, z=479,81], EntityZombie['Zombie'/6835, l='MpServer', x=1831,50, y=56,00, z=417,50], EntitySkeleton['Skeleton'/6645, l='MpServer', x=1711,91, y=56,00, z=518,91], EntityCreeper['Creeper'/6646, l='MpServer', x=1810,50, y=56,00, z=473,50], EntityZombie['Zombie'/6966, l='MpServer', x=1721,50, y=56,00, z=418,50], EntityCreeper['Creeper'/6967, l='MpServer', x=1711,50, y=56,00, z=418,50], EntitySkeleton['Skeleton'/6839, l='MpServer', x=1718,50, y=56,00, z=424,50], EntityZombie['Zombie'/6968, l='MpServer', x=1725,50, y=56,00, z=415,50], EntityCreeper['Creeper'/6970, l='MpServer', x=1749,50, y=56,00, z=405,50], EntitySkeleton['Skeleton'/6971, l='MpServer', x=1745,50, y=56,00, z=410,50], EntitySkeleton['Skeleton'/6972, l='MpServer', x=1714,50, y=56,00, z=525,50], EntityCreeper['Creeper'/6973, l='MpServer', x=1749,50, y=56,00, z=404,50], EntityZombie['Zombie'/6782, l='MpServer', x=1758,50, y=56,00, z=412,50], EntityCreeper['Creeper'/6974, l='MpServer', x=1718,56, y=56,00, z=526,31], EntityCreeper['Creeper'/6975, l='MpServer', x=1721,50, y=56,00, z=526,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 69987048 bytes (66 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.140.1401 Minecraft Forge 10.13.3.1401 Optifine OptiFine_1.7.10_HD_U_B7 63 mods loaded, 63 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.140.1401} [Forge Mod Loader](forge-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.3.1401} [Minecraft Forge](forge-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.6.43} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.4.106} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.106-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsCore{0.7.3} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.2} [CoFH Core](CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{6.4.14} [BuildCraft](buildcraft-6.4.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{6.4.14} [BC Transport](buildcraft-6.4.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{6.4.14} [BC Silicon](buildcraft-6.4.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{6.4.14} [BC Builders](buildcraft-6.4.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{6.4.14} [BC Energy](buildcraft-6.4.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{6.4.14} [BC Factory](buildcraft-6.4.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ComputerCraft{1.73} [ComputerCraft](ComputerCraft1.73.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MrTJPCoreMod{1.0.6.13} [MrTJPCore](MrTJPCore-1.0.6.13-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeRelocation{0.0.1a.1} [ForgeRelocation](ForgeRelocation-1.7.10-0.0.1a.1-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftCore{3.0.11} [Galacticraft Core](GalacticraftCore-1.7-3.0.11.334.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GalacticraftMars{3.0.11} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.11.334.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{6.0.60.741} [Iron Chest](ironchest-1.7.10-6.0.60.741-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.1.2.334} [Forge Multipart](ForgeMultipart-1.7.10-1.1.2.334-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Core{4.6.0.79} [ProjectRed](ProjectRed-1.7.10-4.6.0.79-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Exploration{4.6.0.79} [ProjectRed-Exploration](ProjectRed-1.7.10-4.6.0.79-World.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenMods{0.7.3} [OpenMods](OpenModsLib-1.7.10-0.7.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenBlocks{1.4.3} [OpenBlocks](OpenBlocks-1.7.10-1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transmission{4.6.0.79} [ProjectRed-Transmission](ProjectRed-1.7.10-4.6.0.79-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transportation{4.6.0.79} [ProjectRed-Transportation](ProjectRed-1.7.10-4.6.0.79-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Compatibility{4.6.0.79} [ProjectRed-Compatibility](ProjectRed-1.7.10-4.6.0.79-Compat.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Integration{4.6.0.79} [ProjectRed-Integration](ProjectRed-1.7.10-4.6.0.79-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Illumination{4.6.0.79} [ProjectRed-Illumination](ProjectRed-1.7.10-4.6.0.79-Lighting.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Expansion{4.6.0.79} [ProjectRed-Expansion](ProjectRed-1.7.10-4.6.0.79-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    simply_sit{1.7.10-1.1.0} [Simply Sit](SimplySit-1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.0.0-122.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.1.2.334} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.2.334-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.1.2.334} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.2.334-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    CoFHCore: -[1.7.10]3.0.2-262
    ThermalFoundation: -[1.7.10]1.0.0-81
    ThermalExpansion: -[1.7.10]4.0.1-182
    MineFactoryReloaded: -[1.7.10]2.8.0-104
    ThermalDynamics: -[1.7.10]1.0.0-122
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    Launched Version: 1.7.10-Forge10.13.3.1401-1710ls
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3412, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Zedrimar** [comment]
This is likely caused by optifine, either use default or smooth chunk loading (multicore causes many issues anyways such as disapearing blocks to name a few) or disable connected textures if it happens again, if all else fails let me know. Also, next time use something like http://paste.ubuntu.com/ for crashlogs etc.

Also try Fastcraft (if you need a performance boost) by it self or with optifine and that can help a bunch and may even solve the issue
