### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by minecraftlogie** [erogenousbeef/BigReactors#530]
[17:24:01] [main/INFO]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[17:24:01] [main/INFO]: Using primary tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[17:24:01] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[17:24:02] [main/INFO]: Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker
[17:24:02] [main/INFO]: Bootstrapping LiteLoader 1.7.10
[17:24:02] [main/INFO]: Registering API provider class com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient
[17:24:02] [main/INFO]: Spawning API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' ...
[17:24:03] [main/INFO]: API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' provides API 'liteloader'
[17:24:03] [main/INFO]: Initialising API 'liteloader' ...
[17:24:03] [main/INFO]: LiteLoader begin PREINIT...
[17:24:03] [main/INFO]: Initialising Loader properties...
[17:24:03] [main/INFO]: Setting up logger...
[17:24:03] [main/INFO]: LiteLoader 1.7.10_04 starting up...
[17:24:03] [main/INFO]: Java reports OS="windows 8.1"
[17:24:03] [main/INFO]: Enumerating class path...
[17:24:03] [main/INFO]: Class path separator=";"
[17:24:03] [main/INFO]: Class path entries=(
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\mumfrey\liteloader\1.7.10\liteloader-1.7.10.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\net\minecraft\launchwrapper\1.11\launchwrapper-1.11.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\google\guava\guava\16.0\guava-16.0.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\net\minecraftforge\forge\1.7.10-10.13.4.1448-1.7.10\forge-1.7.10-10.13.4.1448-1.7.10.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\net\minecraft\launchwrapper\1.11\launchwrapper-1.11.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\mojang\realms\1.3.5\realms-1.3.5.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\java3d\vecmath\1.3.1\vecmath-1.3.1.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\google\guava\guava\15.0\guava-15.0.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\libraries\tv\twitch\twitch\5.16\twitch-5.16.jar
   classpathEntry=C:\Users\logan\AppData\Roaming.minecraft\versions\1.7.10\1.7.10.jar
)
[17:24:03] [main/INFO]: Registering discovery module EnumeratorModuleClassPath: [<Java Class Path>]
[17:24:03] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [C:\Users\logan\AppData\Roaming.minecraft\mods]
[17:24:03] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [C:\Users\logan\AppData\Roaming.minecraft\mods\1.7.10]
[17:24:03] [main/INFO]: Adding supported mod class prefix 'LiteMod'
[17:24:03] [main/INFO]: Discovering tweaks on class path...
[17:24:03] [main/INFO]: Discovering valid mod files in folder C:\Users\logan\AppData\Roaming.minecraft\mods
[17:24:03] [main/INFO]: Considering valid mod file: C:\Users\logan\AppData\Roaming.minecraft\mods\mod_voxelMap_1.5.5_for_1.7.10.litemod
[17:24:03] [main/INFO]: Adding newest valid mod file 'C:\Users\logan\AppData\Roaming.minecraft\mods\mod_voxelMap_1.5.5_for_1.7.10.litemod' at revision 1505.0000
[17:24:03] [main/INFO]: Discovering valid mod files in folder C:\Users\logan\AppData\Roaming.minecraft\mods\1.7.10
[17:24:03] [main/INFO]: Searching for tweaks in 'CodeChickenLib-1.7.10-1.1.1.99-universal.jar'
[17:24:03] [main/WARN]: Error parsing manifest entries in 'C:\Users\logan\AppData\Roaming.minecraft\mods\1.7.10\CodeChickenLib-1.7.10-1.1.1.99-universal.jar'
[17:24:03] [main/INFO]: Searching for tweaks in '[1.7.10]bspkrsCore-universal-6.15.jar'
[17:24:03] [main/WARN]: Error parsing manifest entries in 'C:\Users\logan\AppData\Roaming.minecraft\mods\1.7.10[1.7.10]bspkrsCore-universal-6.15.jar'
[17:24:03] [main/INFO]: Mod file 'mod_voxelMap_1.5.5_for_1.7.10.litemod' provides classTransformer 'com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer', adding to class loader
[17:24:03] [main/INFO]: classTransformer 'com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer' was successfully added
[17:24:03] [main/INFO]: LiteLoader PREINIT complete
[17:24:03] [main/INFO]: Sorting registered packet transformers by priority
[17:24:03] [main/INFO]: Added 0 packet transformer classes to the transformer list
[17:24:03] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.transformers.event.EventProxyTransformer'
[17:24:03] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.launch.LiteLoaderTransformer'
[17:24:03] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.client.transformers.CrashReportTransformer'
[17:24:03] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer'
[17:24:03] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer'
[17:24:04] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer'
[17:24:04] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[17:24:04] [main/INFO]: Forge Mod Loader version 7.99.16.1448 for Minecraft 1.7.10 loading
[17:24:04] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_51
[17:24:04] [main/WARN]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:24:05] [main/WARN]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:24:05] [main/WARN]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:24:05] [main/WARN]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:24:05] [main/INFO]: [AppEng] Core Init
[17:24:05] [main/WARN]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:24:05] [main/WARN]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:24:05] [main/WARN]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:24:05] [main/WARN]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:24:05] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:24:05] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[17:24:05] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:24:05] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:24:05] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:24:12] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[17:24:12] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[17:24:12] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:24:12] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:24:12] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:24:12] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:24:13] [main/INFO]: Loaded library ejml-0.23.jar.
[17:24:13] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:24:13] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:24:13] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:102]: Successfully Registered Transformer
[17:24:15] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[17:24:15] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:295]: [Micdoodle8Core]: Patching game...
[17:24:15] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:24:16] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:24:16] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:24:16] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[17:24:18] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:24:18] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:24:18] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[17:24:18] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[17:24:18] [main/INFO]: Injecting downstream transformers
[17:24:18] [main/INFO]: Injecting additional class transformer class 'com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer'
[17:24:19] [main/INFO]: Injecting additional class transformer class 'com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer'
[17:24:19] [main/INFO]: Injecting additional class transformer class 'com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer'
[17:24:19] [main/INFO]: Injecting additional class transformer class 'com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer'
[17:24:20] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[17:24:22] [main/INFO]: Injecting onstartupcomplete[x1] in func_71384_a in Minecraft
[17:24:22] [main/INFO]: Injecting prerenderfbo[x1] in func_71411_J in Minecraft
[17:24:22] [main/INFO]: Injecting postrenderfbo[x1] in func_71411_J in Minecraft
[17:24:22] [main/INFO]: Injecting ontimerupdate[x1] in func_71411_J in Minecraft
[17:24:22] [main/INFO]: Injecting onrender[x1] in func_71411_J in Minecraft
[17:24:22] [main/INFO]: Injecting ontick[x1] in func_71411_J in Minecraft
[17:24:22] [main/INFO]: Injecting shutdown[x1] in func_71400_g in Minecraft
[17:24:22] [main/INFO]: Injecting updateframebuffersize[x1] in func_147119_ah in Minecraft
[17:24:23] [main/INFO]: Injecting newtick[x1] in func_71407_l in Minecraft
[17:24:23] [main/INFO]: Applying overlay com.mumfrey.liteloader.client.overlays.MinecraftOverlay to net.minecraft.client.Minecraft
[17:24:23] [main/INFO]: MinecraftOverlayTransformer found INIT injection point, this is good.
[17:24:24] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: sv (1 / 1)
[17:24:24] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1848]: Galacticraft successfully injected bytecode into: sa (1 / 1)
[17:24:24] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer
    at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayer
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/EntityLivingBase
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.EntityLivingBase
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/Entity
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.Entity
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
    ... 6 more
Caused by: java.lang.ClassFormatError: Duplicate method name&signature in class file net/minecraft/entity/Entity
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
    at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
    ... 6 more

**Comment by RogueLogix** [comment]
just your game. mine launches fine.

**Comment by minecraftlogie** [comment]
ok

**Comment by RogueLogix** [comment]
to be exact it launches fine with over 200 other mods. i suggest reinstalling whatever modpack you have. if that doesn't work add more ram to minecraft. and if both of those things don't work try updating java.

**Comment by minecraftlogie** [comment]
it work thanks!
