### ISSUE TITLE
Client Crash [1.7.10]

### ISSUE THREAD

**Issue by ShadowstarPRO** [erogenousbeef/BigReactors#587]
Hello, I am playing a server with my friends, and BigReactors is one of the mods that we have. The server was working fine for a few days, but now as soon as the server loads, my client crashes. This is the crash report that I receive. I noticed that BigReactors was at the head of the crash, so I thought I might ask about it here. I read the thread about what looks like this, but I could not find the item ID section to change the item IDs in the config folder of the server. Please help, because I have no idea how to fix this, and I have been researching this for awhile. Here is the crash report I receive: 

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 12/29/16 6:05 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Unrecognized metadata
	at erogenousbeef.bigreactors.common.multiblock.block.BlockMultiblockGlass.func_149915_a(BlockMultiblockGlass.java:58)
	at net.minecraft.block.Block.createTileEntity(Block.java:1446)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.World.func_147438_o(World.java:2540)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1118)
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at erogenousbeef.bigreactors.common.multiblock.block.BlockMultiblockGlass.func_149915_a(BlockMultiblockGlass.java:58)
	at net.minecraft.block.Block.createTileEntity(Block.java:1446)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.World.func_147438_o(World.java:2540)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1118)
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Shadowstar_PRO'/6614, l='MpServer', x=55.50, y=91.62, z=110.50]]
	Chunk stats: MultiplayerChunkCache: 35, 35
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (60,64,104), Chunk: (at 12,4,8 in 3,6; contains blocks 48,0,96 to 63,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3535730 game time, 3902685 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 156 total; [EntityItem['item.item.GlowstoneSeeds'/4096, l='MpServer', x=80.16, y=41.13, z=140.13], EntityItem['item.item.GlowstoneSeeds'/4097, l='MpServer', x=86.75, y=35.13, z=129.34], EntityLootableBody['Corpse'/4098, l='MpServer', x=87.41, y=65.00, z=128.41], EntityItem['item.item.GlowstoneSeeds'/3850, l='MpServer', x=78.38, y=2.13, z=70.13], EntityItem['item.item.GlowstoneSeeds'/3853, l='MpServer', x=73.78, y=25.13, z=76.13], EntityItem['item.item.GlowstoneSeeds'/3086, l='MpServer', x=23.75, y=14.13, z=68.88], EntityItem['item.item.GlowstoneSeeds'/3854, l='MpServer', x=66.56, y=17.13, z=66.88], EntityItem['item.item.GlowstoneSeeds'/3087, l='MpServer', x=31.13, y=15.13, z=74.13], EntityItem['item.item.GlowstoneSeeds'/3855, l='MpServer', x=69.13, y=35.13, z=73.13], EntityItem['item.item.GlowstoneSeeds'/3088, l='MpServer', x=17.13, y=31.13, z=75.13], EntityLootableBody['Corpse'/3856, l='MpServer', x=64.41, y=69.00, z=67.41], EntityItem['item.item.GlowstoneSeeds'/3857, l='MpServer', x=64.22, y=11.13, z=93.88], EntityItem['item.item.GlowstoneSeeds'/3089, l='MpServer', x=26.47, y=19.13, z=68.47], EntityItem['item.item.GlowstoneSeeds'/3858, l='MpServer', x=78.13, y=26.13, z=85.88], EntityItem['item.item.GlowstoneSeeds'/3090, l='MpServer', x=20.75, y=30.13, z=75.75], EntityItem['item.item.GlowstoneSeeds'/3859, l='MpServer', x=65.13, y=21.13, z=80.13], EntityItem['item.item.GlowstoneSeeds'/3091, l='MpServer', x=19.16, y=41.13, z=72.13], EntityItem['item.item.GlowstoneSeeds'/3860, l='MpServer', x=79.13, y=34.13, z=82.13], EntityItem['item.item.GlowstoneSeeds'/3092, l='MpServer', x=30.13, y=32.13, z=73.88], EntityItem['item.item.GlowstoneSeeds'/3604, l='MpServer', x=51.13, y=10.13, z=79.47], EntityItem['item.item.GlowstoneSeeds'/3861, l='MpServer', x=78.75, y=36.13, z=90.69], EntityItem['item.item.GlowstoneSeeds'/3605, l='MpServer', x=55.88, y=31.13, z=72.13], EntityClientPlayerMP['Shadowstar_PRO'/6614, l='MpServer', x=55.50, y=91.62, z=110.50], EntityItem['item.item.GlowstoneSeeds'/3862, l='MpServer', x=78.63, y=7.13, z=110.03], EntityBat['Bat'/3094, l='MpServer', x=20.50, y=25.09, z=87.75], EntityItem['item.item.GlowstoneSeeds'/3606, l='MpServer', x=50.13, y=31.13, z=72.28], EntityBat['Bat'/3095, l='MpServer', x=16.75, y=18.09, z=83.75], EntityHidingFungi['Hiding Fungi'/3607, l='MpServer', x=60.50, y=69.00, z=75.50], EntityItem['item.item.GlowstoneSeeds'/3864, l='MpServer', x=66.84, y=23.13, z=97.13], EntityItem['item.item.GlowstoneSeeds'/3608, l='MpServer', x=62.22, y=15.13, z=89.88], EntityBat['Bat'/3096, l='MpServer', x=21.44, y=27.09, z=84.25], EntityItem['item.item.GlowstoneSeeds'/3865, l='MpServer', x=69.22, y=29.13, z=99.53], EntityItem['item.item.GlowstoneSeeds'/3609, l='MpServer', x=61.13, y=16.13, z=88.88], EntityItem['item.item.GlowstoneSeeds'/3097, l='MpServer', x=21.63, y=25.13, z=80.22], EntityItem['item.item.GlowstoneSeeds'/3098, l='MpServer', x=30.88, y=24.13, z=93.88], EntityItem['item.item.GlowstoneSeeds'/3611, l='MpServer', x=50.22, y=42.13, z=85.13], EntityCreeper['Creeper'/3099, l='MpServer', x=19.69, y=26.00, z=88.31], EntityItem['item.item.GlowstoneSeeds'/3355, l='MpServer', x=43.13, y=21.13, z=75.13], EntityItem['item.item.GlowstoneSeeds'/3612, l='MpServer', x=55.13, y=21.13, z=102.13], EntityItem['item.item.GlowstoneSeeds'/3868, l='MpServer', x=66.88, y=6.13, z=123.13], EntityBat['Bat'/3100, l='MpServer', x=16.56, y=37.09, z=91.84], EntityItem['item.item.GlowstoneSeeds'/3356, l='MpServer', x=37.13, y=24.13, z=70.28], EntityItem['item.item.GlowstoneSeeds'/3613, l='MpServer', x=48.28, y=16.13, z=109.41], EntityItem['item.item.GlowstoneSeeds'/3869, l='MpServer', x=70.66, y=8.13, z=121.88], EntityCreeper['Creeper'/3101, l='MpServer', x=31.00, y=41.00, z=88.56], EntityItem['item.item.GlowstoneSeeds'/3614, l='MpServer', x=55.88, y=21.13, z=102.13], EntityItem['item.item.GlowstoneSeeds'/3870, l='MpServer', x=79.13, y=20.13, z=125.13], EntityLootableBody['Corpse'/3358, l='MpServer', x=47.25, y=72.00, z=73.31], EntityItem['item.item.GlowstoneSeeds'/3615, l='MpServer', x=60.13, y=33.13, z=111.88], EntityItem['item.item.GlowstoneSeeds'/3871, l='MpServer', x=75.34, y=29.13, z=124.13], EntitySkeleton['Skeleton'/3359, l='MpServer', x=32.50, y=12.00, z=95.50], EntityItem['item.item.GlowstoneSeeds'/3103, l='MpServer', x=22.84, y=21.13, z=105.78], EntityLootableBody['Corpse'/3616, l='MpServer', x=60.81, y=78.00, z=100.44], EntityItem['item.item.GlowstoneSeeds'/3360, l='MpServer', x=42.34, y=7.13, z=95.88], EntityItem['item.item.GlowstoneSeeds'/3104, l='MpServer', x=31.13, y=8.13, z=126.28], EntityItem['item.item.GlowstoneSeeds'/3617, l='MpServer', x=56.22, y=13.13, z=118.88], EntityItem['item.item.GlowstoneSeeds'/3361, l='MpServer', x=41.34, y=5.13, z=84.59], EntityItem['item.item.GlowstoneSeeds'/3874, l='MpServer', x=69.03, y=35.13, z=113.13], EntityItem['item.item.GlowstoneSeeds'/3106, l='MpServer', x=21.13, y=26.13, z=121.13], EntityItem['item.item.GlowstoneSeeds'/3875, l='MpServer', x=67.88, y=37.13, z=117.50], EntityItem['item.item.GlowstoneSeeds'/3619, l='MpServer', x=62.13, y=27.13, z=118.88], EntityItem['item.item.GlowstoneSeeds'/3363, l='MpServer', x=32.66, y=21.13, z=94.13], EntityItem['item.item.GlowstoneSeeds'/3107, l='MpServer', x=29.88, y=28.13, z=119.88], EntityHidingFungi['Hiding Fungi'/3876, l='MpServer', x=79.50, y=77.00, z=114.50], EntityBat['Bat'/3620, l='MpServer', x=58.78, y=43.09, z=113.97], EntityItem['item.item.GlowstoneSeeds'/3364, l='MpServer', x=46.88, y=24.13, z=93.88], EntityItem['item.item.GlowstoneSeeds'/3108, l='MpServer', x=16.50, y=22.13, z=124.88], EntityItem['item.item.GlowstoneSeeds'/3621, l='MpServer', x=61.25, y=33.13, z=117.38], EntityItem['item.item.GlowstoneSeeds'/3365, l='MpServer', x=33.13, y=19.13, z=82.13], EntityItem['item.item.GlowstoneSeeds'/3877, l='MpServer', x=73.13, y=14.13, z=128.13], EntityItem['item.item.GlowstoneSeeds'/3109, l='MpServer', x=17.88, y=26.13, z=112.59], EntityBat['Bat'/2853, l='MpServer', x=24.66, y=27.16, z=88.31], EntityZombie['Zombie'/3622, l='MpServer', x=63.50, y=108.00, z=116.16], EntityItem['item.item.GlowstoneSeeds'/3366, l='MpServer', x=32.13, y=31.13, z=86.13], EntityItem['item.item.GlowstoneSeeds'/3367, l='MpServer', x=47.22, y=36.13, z=93.03], EntityItem['item.item.GlowstoneSeeds'/3879, l='MpServer', x=74.88, y=31.13, z=142.25], EntityItem['item.item.GlowstoneSeeds'/3623, l='MpServer', x=53.28, y=4.13, z=136.72], EntityItem['item.item.GlowstoneSeeds'/3111, l='MpServer', x=16.13, y=32.13, z=124.59], EntityItem['item.item.GlowstoneSeeds'/3368, l='MpServer', x=32.13, y=26.13, z=109.38], EntityItem['item.item.GlowstoneSeeds'/3880, l='MpServer', x=64.88, y=17.13, z=142.88], EntityItem['item.item.GlowstoneSeeds'/3624, l='MpServer', x=51.88, y=14.13, z=143.63], EntityItem['item.item.GlowstoneSeeds'/3112, l='MpServer', x=17.88, y=32.13, z=125.16], EntityItem['item.item.GlowstoneSeeds'/3369, l='MpServer', x=44.28, y=40.13, z=105.13], EntityItem['item.item.GlowstoneSeeds'/3881, l='MpServer', x=73.88, y=17.13, z=134.13], EntityItem['item.item.GlowstoneSeeds'/3625, l='MpServer', x=51.13, y=29.13, z=137.47], EntityItem['item.item.GlowstoneSeeds'/3113, l='MpServer', x=17.41, y=41.13, z=115.59], EntityLootableBody['Corpse'/3370, l='MpServer', x=36.84, y=80.00, z=96.06], EntityItem['item.item.GlowstoneSeeds'/3882, l='MpServer', x=72.72, y=29.13, z=133.88], EntityItem['item.item.GlowstoneSeeds'/3626, l='MpServer', x=62.19, y=28.13, z=143.22], EntityLootableBody['Corpse'/3114, l='MpServer', x=17.56, y=96.00, z=123.56], EntityItem['item.item.GlowstoneSeeds'/3371, l='MpServer', x=34.53, y=9.13, z=117.31], EntityItem['item.item.GlowstoneSeeds'/3883, l='MpServer', x=76.13, y=34.13, z=128.78], EntityItem['item.item.GlowstoneSeeds'/3372, l='MpServer', x=41.09, y=17.13, z=125.69], EntityItem['item.item.GlowstoneSeeds'/3884, l='MpServer', x=79.53, y=42.13, z=139.38], EntityItem['item.item.GlowstoneSeeds'/3116, l='MpServer', x=27.13, y=37.13, z=138.44], EntityZombie['Zombie'/3885, l='MpServer', x=67.97, y=71.00, z=140.47], EntityItem['item.item.GlowstoneSeeds'/3374, l='MpServer', x=34.31, y=7.13, z=137.78], EntityItem['item.item.GlowstoneSeeds'/3375, l='MpServer', x=43.88, y=10.13, z=131.13], EntityLootableBody['Corpse'/3376, l='MpServer', x=34.31, y=17.00, z=134.28], EntityItem['item.item.GlowstoneSeeds'/3377, l='MpServer', x=36.66, y=30.13, z=140.13], EntityLootableBody['Corpse'/3378, l='MpServer', x=34.41, y=57.00, z=132.41], EntityPortalMaster['Portal Master'/3379, l='MpServer', x=38.47, y=152.00, z=142.16], EntityPortalMaster['Portal Master'/3380, l='MpServer', x=36.22, y=152.00, z=141.19], EntityPortalMaster['Portal Master'/3381, l='MpServer', x=37.50, y=152.00, z=140.91], EntityPortalMaster['Portal Master'/3382, l='MpServer', x=40.03, y=151.00, z=142.50], EntityPortalMaster['Portal Master'/3383, l='MpServer', x=43.03, y=151.00, z=142.91], EntityItem['item.item.GlowstoneSeeds'/4301, l='MpServer', x=99.72, y=23.13, z=64.13], EntityItem['item.item.GlowstoneSeeds'/4302, l='MpServer', x=100.13, y=21.13, z=74.84], EntityItem['item.item.GlowstoneSeeds'/4303, l='MpServer', x=100.13, y=34.13, z=70.13], EntityCyclops['Cyclops'/4304, l='MpServer', x=105.06, y=71.00, z=73.88], EntityItem['item.item.GlowstoneSeeds'/4305, l='MpServer', x=108.59, y=6.13, z=91.63], EntityItem['item.item.GlowstoneSeeds'/4306, l='MpServer', x=109.13, y=29.13, z=93.13], EntityItem['item.item.GlowstoneSeeds'/4308, l='MpServer', x=97.13, y=34.13, z=87.69], EntityLootableBody['Corpse'/4309, l='MpServer', x=100.44, y=71.00, z=90.56], EntitySheep['Sheep'/4310, l='MpServer', x=96.50, y=72.00, z=91.78], EntityLootableBody['Corpse'/4311, l='MpServer', x=100.56, y=5.00, z=98.69], EntityItem['item.item.GlowstoneSeeds'/4312, l='MpServer', x=104.13, y=15.13, z=108.88], EntityItem['item.item.GlowstoneSeeds'/4313, l='MpServer', x=103.88, y=7.13, z=110.66], EntityBat['Bat'/4314, l='MpServer', x=96.75, y=24.09, z=110.75], EntityItem['item.item.GlowstoneSeeds'/4316, l='MpServer', x=103.72, y=16.13, z=109.88], EntityItem['item.item.GlowstoneSeeds'/4319, l='MpServer', x=107.88, y=5.13, z=115.88], EntityBat['Bat'/4320, l='MpServer', x=96.25, y=23.09, z=113.53], EntityBat['Bat'/4321, l='MpServer', x=96.56, y=23.09, z=123.56], EntityItem['item.item.GlowstoneSeeds'/4322, l='MpServer', x=105.13, y=22.13, z=118.88], EntityItem['item.item.GlowstoneSeeds'/4323, l='MpServer', x=111.13, y=38.13, z=118.56], EntityItem['item.item.GlowstoneSeeds'/4068, l='MpServer', x=88.38, y=25.13, z=67.50], EntityItem['item.item.GlowstoneSeeds'/4324, l='MpServer', x=96.13, y=37.13, z=114.19], EntityItem['item.item.GlowstoneSeeds'/4069, l='MpServer', x=94.22, y=10.13, z=87.00], EntityItem['item.item.GlowstoneSeeds'/4325, l='MpServer', x=96.88, y=36.13, z=119.13], EntityItem['item.item.GlowstoneSeeds'/4070, l='MpServer', x=91.13, y=9.13, z=81.91], EntityBat['Bat'/8678, l='MpServer', x=72.47, y=10.00, z=128.47], EntityItem['item.item.GlowstoneSeeds'/4327, l='MpServer', x=105.81, y=7.13, z=131.22], EntityBat['Bat'/4073, l='MpServer', x=91.56, y=49.09, z=88.03], EntityItem['item.item.GlowstoneSeeds'/4330, l='MpServer', x=104.88, y=16.13, z=141.53], EntityItem['item.item.GlowstoneSeeds'/4075, l='MpServer', x=83.13, y=15.13, z=98.13], EntityItem['item.item.GlowstoneSeeds'/4331, l='MpServer', x=104.19, y=16.13, z=129.59], EntityItem['item.item.GlowstoneSeeds'/4332, l='MpServer', x=107.84, y=17.13, z=142.88], EntityCreeper['Creeper'/4333, l='MpServer', x=109.97, y=36.00, z=143.50], EntityItem['item.item.GlowstoneSeeds'/4078, l='MpServer', x=91.13, y=24.13, z=110.88], EntityItem['item.item.GlowstoneSeeds'/4335, l='MpServer', x=97.13, y=37.13, z=139.69], EntityGhostineAncient['Ghostine Ancient'/4080, l='MpServer', x=87.25, y=71.00, z=97.75], EntityTaintSporeSwarmer['Taint Spore Swarmer'/4336, l='MpServer', x=105.50, y=66.00, z=140.50], EntityItem['item.item.GlowstoneSeeds'/4081, l='MpServer', x=85.13, y=2.13, z=113.13], EntityItem['item.item.GlowstoneSeeds'/4082, l='MpServer', x=91.88, y=11.13, z=124.13], EntityItem['item.item.GlowstoneSeeds'/8691, l='MpServer', x=36.81, y=11.69, z=88.78], EntityItem['item.item.GlowstoneSeeds'/4083, l='MpServer', x=82.59, y=13.13, z=117.13], EntityItem['item.item.GlowstoneSeeds'/4084, l='MpServer', x=87.72, y=8.13, z=119.34], EntityItem['item.item.GlowstoneSeeds'/4085, l='MpServer', x=92.31, y=1.13, z=117.19], EntityItem['item.item.GlowstoneSeeds'/4086, l='MpServer', x=81.88, y=8.13, z=116.88], EntityThaumicSlime['Thaumic Slime'/4087, l='MpServer', x=93.53, y=19.00, z=125.44], EntityItem['item.item.GlowstoneSeeds'/4089, l='MpServer', x=95.44, y=37.13, z=115.72], EntityLootableBody['Corpse'/4090, l='MpServer', x=80.78, y=76.00, z=116.22], EntityItem['item.item.GlowstoneSeeds'/4092, l='MpServer', x=92.19, y=11.13, z=134.88], EntityItem['item.item.GlowstoneSeeds'/4093, l='MpServer', x=93.34, y=8.13, z=141.44], EntityCreeper['Creeper'/4606, l='MpServer', x=107.78, y=62.41, z=123.88], EntityItem['item.item.GlowstoneSeeds'/4095, l='MpServer', x=90.81, y=23.13, z=141.88]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.11.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 236114008 bytes (225 MB) / 693653504 bytes (661 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 CoFHTweaks v1.1.2 Minecraft Forge 10.13.4.1614 46 mods loaded, 46 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal 7.52.59 PM.jar) 
	UCHIJA	VeinMiner_coremod{0.21.2_build-43} [Core mod] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	<CoFH Tweak>{1.7.10R1.1.2} [CoFH Tweak ASM] (CoFHTweaks-[1.7.10]1.1.2-89 7.52.59 PM.jar) 
	UCHIJA	nevermine{1.1.1} [Nevermine] (AdventOfAscensionV2.0 7.52.59 PM.jar) 
	UCHIJA	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0 7.52.59 PM.jar) 
	UCHIJA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10-2 7.52.59 PM.jar) 
	UCHIJA	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327 7.52.59 PM.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJA	ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.5-115 7.52.59 PM.jar) 
	UCHIJA	ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.4-247 7.52.59 PM.jar) 
	UCHIJA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A-2 5.55.33 PM.jar) 
	UCHIJA	cfm{3.4.8} [�9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10 7.52.59 PM.jar) 
	UCHIJA	lootablebodies{1.3.7} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.7.10-backport_1.3.7-2 7.52.59 PM.jar) 
	UCHIJA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJA	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281 7.52.59 PM.jar) 
	UCHIJA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJA	EnderStorage{1.4.7.38} [EnderStorage] (EnderStorage-1.7.10-1.4.7.38-universal 7.52.59 PM.jar) 
	UCHIJA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b197-2 7.52.59 PM.jar) 
	UCHIJA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2 7.52.59 PM.jar) 
	UCHIJA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8 7.52.59 PM.jar) 
	UCHIJA	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3 7.52.59 PM.jar) 
	UCHIJA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2 7.52.59 PM.jar) 
	UCHIJA	InventoryPets{1.3.9} [Inventory Pets] (inventorypets-1.7.10-1.3.9-universal 7.52.59 PM.jar) 
	UCHIJA	magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core] (magicalcrops-4.0.0_PUBLIC_BETA_5 7.52.59 PM.jar) 
	UCHIJA	magicalcropsarmour{4.0.0_PUBLIC_BETA_4} [Magical Crops: Armoury] (magicalcropsarmoury-4.0.0_PUBLIC_BETA_4 7.52.59 PM.jar) 
	UCHIJA	MCEF{0.6} [Minecraft Chromium Embedded Framework] (MCEF-1.7.10 7.52.59 PM.jar) 
	UCHIJA	MekanismTools{8.1.9} [MekanismTools] (MekanismTools-1.7.10-8.1.9.265 7.52.59 PM.jar) 
	UCHIJA	numina{0.4.0.100} [Numina] (Numina-Mod-1.7.10 7.52.59 PM.jar) 
	UCHIJA	powersuits{0.11.0.176} [MachineMuse's Modular Powersuits] (Modular-Powersuits-Mod-1.7.10 7.52.59 PM.jar) 
	UCHIJA	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22 7.52.59 PM.jar) 
	UCHIJA	PortalGun{4.0.0-beta-6} [PortalGun] (Portal-Gun-Mod-1.7.10 7.52.59 PM.jar) 
	UCHIJA	RedstoneArsenal{1.7.10R1.1.2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.2-92 7.52.59 PM.jar) 
	UCHIJA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413 7.52.59 PM.jar) 
	UCHIJA	SimpleAchievements{MC1.7.10-1.1.0-21} [Simple Achievements] (Simple-Achievements-Mod-1.7.10 7.52.59 PM.jar) 
	UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5 7.52.59 PM.jar) 
	UCHIJA	ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.0-171 7.52.59 PM.jar) 
	UCHIJA	VeinMiner{0.21.2} [Vein Miner] (VeinMiner-1.7.10_0.21.2.43 7.52.59 PM.jar) 
	UCHIJA	VeinMinerModSupport{0.21.2} [Mod Support] (VeinMiner-1.7.10_0.21.2.43 7.52.59 PM.jar) 
	UCHIJA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.14.66' Renderer: 'Intel(R) HD Graphics 6000'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.1.3-327
	ThermalFoundation: -[1.7.10]1.2.5-115
	ThermalExpansion: -[1.7.10]4.1.4-247
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.1-22
	RedstoneArsenal: -[1.7.10]1.1.2-92
	ThermalDynamics: -[1.7.10]1.2.0-171
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 6000 GL version 2.1 INTEL-10.14.66, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

Thank you for the help! If you need my game output, it is very long so I will attach it as a pastebin. http://pastebin.com/DpZYwtTj

THANK YOU SO MUCH!!!! We appreciate it greatly....

**Comment by RogueLogix** [comment]
1st please use pastebin for the output, all of it.
2nd Please read erogenousbeef/BigReactors#583
